"""
Configuration file for network traffic anomaly detection project.
Contains file paths and column definitions used across the project.
"""

# Raw data file paths
FILE_PATHS = [
    'data/raw/Monday-WorkingHours.pcap_ISCX.csv',
    'data/raw/Tuesday-WorkingHours.pcap_ISCX.csv',
    'data/raw/Wednesday-WorkingHours.pcap_ISCX.csv',
    'data/raw/Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv',
    'data/raw/Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv',
    'data/raw/Friday-WorkingHours-Morning.pcap_ISCX.csv',
    'data/raw/Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv',
    'data/raw/Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv',
]

COLUMNS = [
    'Destination Port',
    'Flow Duration',
    'Total Fwd Packets',
    'Total Backward Packets',
    'Total Length of Fwd Packets',
    'Total Length of Bwd Packets',
    'Fwd Packet Length Max',
    'Fwd Packet Length Min',
    'Fwd Packet Length Mean',
    'Fwd Packet Length Std',
    'Bwd Packet Length Max',
    'Bwd Packet Length Min',
    'Bwd Packet Length Mean',
    'Bwd Packet Length Std',
    'Flow Bytes/s',
    'Flow Packets/s',
    'Flow IAT Mean',
    'Flow IAT Std',
    'Flow IAT Max',
    'Flow IAT Min',
    'Fwd IAT Total',
    'Fwd IAT Mean',
    'Fwd IAT Std',
    'Fwd IAT Max',
    'Fwd IAT Min',
    'Bwd IAT Total',
    'Bwd IAT Mean',
    'Bwd IAT Std',
    'Bwd IAT Max',
    'Bwd IAT Min',
    'Fwd PSH Flags',
    'Bwd PSH Flags',
    'Fwd URG Flags',
    'Bwd URG Flags',
    'Fwd Header Length34',
    'Bwd Header Length',
    'Fwd Packets/s',
    'Bwd Packets/s',
    'Min Packet Length',
    'Max Packet Length',
    'Packet Length Mean',
    'Packet Length Std',
    'Packet Length Variance',
    'FIN Flag Count',
    'SYN Flag Count',
    'RST Flag Count',
    'PSH Flag Count',
    'ACK Flag Count',
    'URG Flag Count',
    'CWE Flag Count',
    'ECE Flag Count',
    'Down/Up Ratio',
    'Average Packet Size',
    'Avg Fwd Segment Size',
    'Avg Bwd Segment Size',
    'Fwd Header Length55',
    'Fwd Avg Bytes/Bulk',
    'Fwd Avg Packets/Bulk',
    'Fwd Avg Bulk Rate',
    'Bwd Avg Bytes/Bulk',
    'Bwd Avg Packets/Bulk',
    'Bwd Avg Bulk Rate',
    'Subflow Fwd Packets',
    'Subflow Fwd Bytes',
    'Subflow Bwd Packets',
    'Subflow Bwd Bytes',
    'Init_Win_bytes_forward',
    'Init_Win_bytes_backward',
    'act_data_pkt_fwd',
    'min_seg_size_forward',
    'Active Mean',
    'Active Std',
    'Active Max',
    'Active Min',
    'Idle Mean',
    'Idle Std',
    'Idle Max',
    'Idle Min',
    'Label'
]

# Processed data paths
TRAIN_DATA_PATH = 'data/processed/train_data.parquet'
MODEL_PATH = 'models/network_intrusion_detector_model'
# Label mappings for classification
LABEL_MAPPINGS = {
    'BENIGN': 'BENIGN',
    'DDoS': 'DDoS',
    'PortScan': 'PortScan',
    'Heartbleed': 'Heartbleed',
    'DoS': 'DoS',
    'WebAttack': 'WebAttack',
    'BruteForce': 'BruteForce',
    'BotNet': 'BotNet',
}
